create database Billmanagers;
CREATE TABLE PHIEUXUAT(
SOPX INT PRIMARY KEY AUTO_INCREMENT,
NGAYXUAT DATETIME NOT NULL
);
CREATE TABLE VATTU(
MAVTU INT PRIMARY KEY AUTO_INCREMENT,
TENVTU VARCHAR(30)
);
CREATE TABLE PHIEUNHAP(
SOPN INT PRIMARY KEY AUTO_INCREMENT,
NGAYNHAP DATETIME NOT NULL
);
CREATE TABLE CHITIETPHIEUXUAT(
SOPX INT NOT NULL,
FOREIGN KEY (SOPX) REFERENCES PHIEUXUAT(SOPX),
MAVTU INT NOT NULL,
FOREIGN KEY (MAVTU) REFERENCES VATTU(MAVTU),
DGXUAT INT NOT NULL,
SLXUAT INT NOT NULL
);
CREATE TABLE CHITIETPHIEUNHAP(
MAVTU INT NOT NULL,
FOREIGN KEY (MAVTU) REFERENCES VATTU(MAVTU),
SOPN INT NOT NULL,
FOREIGN KEY(SOPN) REFERENCES PHIEUNHAP(SOPN),
DGXUAT INT NOT NULL,
SLXUAT INT NOT NULL
);
CREATE TABLE DONDH(
SODH INT PRIMARY KEY AUTO_INCREMENT,
NGAYDH DATETIME NOT NULL
);
CREATE TABLE CHITIETDONDATHANG(
MAVTU INT NOT NULL,
FOREIGN KEY (MAVTU) REFERENCES VATTU(MAVTU),
SODH INT NOT NULL,
FOREIGN KEY (SODH) REFERENCES DONDH(SODH)
);
CREATE TABLE NHACC(
MANCC INT PRIMARY KEY AUTO_INCREMENT,
TENCC VARCHAR(50) NOT NULL,
DIACHI VARCHAR(50) NOT NULL,
SDT VARCHAR(50) NOT NULL
);
CREATE TABLE CUNGCAP(
SODH INT NOT NULL,
FOREIGN KEY(SODH) REFERENCES DONDH(SODH),
MANCC INT NOT NULL,
FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC)
)
